version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pa$$w0rd
      MYSQL_DATABASE: github
      MYSQL_USER: github
      MYSQL_PASSWORD: pa$$w0rd
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
