version: '3.1'

services:

  mysql:
    image: mysql:latest
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: github_app
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
